version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=1Secure*Password1
    ports:
      - "1433:1433"
    volumes:
       - sql_data_volume:/var/opt/mssql
  byme.presentation:
    image: ${DOCKER_REGISTRY-}bymepresentation
    build:
      context: .
      dockerfile: ByMe.Presentation/Dockerfile
    depends_on:
     - db
volumes: 
    sql_data_volume: